[build]
  base = "."
  publish = "./build/" # Este é o diretório padrão onde o React cria os arquivos de produção
  command = "npm run build" # Este comando deve construir seu projeto React

[dev]
  command = "npm start" # Comando para iniciar o servidor de desenvolvimento local