[build]
 base: /opt/build/repo
 command: npm run build
 commandOrigin: config
 publish: /opt/build/repo/build
 publishOrigin: config

[dev]
  command = "npm start" # Comando para iniciar o servidor de desenvolvimento local